export const ACTIONS = {

    CATEGORY: {
        CATEGORY_ADD: "ADD[CATEGORY]",
        CATEGORY_DELETE: "DELETE[CATEGORY]",
        CATEGORY_EDIT: "EDIT[CATEGORY]",
    },
    CATEGORY_BY_ID: {
        CATEGORY_BY_ID_ADD: "ADD[CATEGORY_BY_ID]",
        CATEGORY_BY_ID_DELETE: "DELETE[CATEGORY_BY_ID]",
        CATEGORY_BY_ID_EDIT: "EDIT[CATEGORY_BY_ID]",
    },
    OPTIONS: {
        OPTIONS_ADD: "ADD[OPTIONS]",
        OPTIONS_DELETE: "DELETE[OPTIONS]",
        OPTIONS_EDIT: "EDIT[OPTIONS]",
    },
    OPTIONS_BY_ID: {
        OPTIONS_BY_ID_ADD: "ADD[OPTIONS_BY_ID]",
        OPTIONS_BY_ID_DELETE: "DELETE[OPTIONS_BY_ID]",
        OPTIONS_BY_ID_EDIT: "EDIT[OPTIONS_BY_ID]",
        OPTIONS_BY_ID_TOGGLE: "TOGGLE[OPTIONS_BY_ID]",
    }
}